routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => 'FrontViewController@index', 'as' => 'front.home']);

Route::get('courses', ['uses' => 'FrontViewController@courses', 'as' => 'front.courses']);

Route::get('event', ['uses' => 'FrontViewController@event', 'as' => 'front.event']);

Route::get('teachers', ['uses' => 'FrontViewController@teachers', 'as' => 'front.teachers']);

Route::get('teachers-details', ['uses' => 'FrontViewController@teacher_detail', 'as' => 'front.teacher-details']);

Route::get('blog', ['uses' => 'FrontViewController@blog', 'as' => 'front.blog']);

Route::get('blog-details', ['uses' => 'FrontViewController@blog_details', 'as' => 'front.blog-detail']);

Route::get('about', ['uses' => 'FrontViewController@about', 'as' => 'front.about']);

Route::get('faq', ['uses' => 'FrontViewController@faq', 'as' => 'front.faq']);

Route::get('galary', ['uses' => 'FrontViewController@galary', 'as' => 'front.galary']);

Route::get('price', ['uses' => 'FrontViewController@price', 'as' => 'front.price']);

Route::get('contact', ['uses' => 'FrontViewController@contact', 'as' => 'front.contact']);


// Theme Forest Admin
Route::prefix('admin')->group(function () {
  Route::get('/', ['uses' => 'BackViewController@index', 'as' => 'back.home']);

  Route::get('students', ['uses' => 'BackViewController@students', 'as' => 'back.students']);

  Route::get('add-students', ['uses' => 'BackViewController@add_students', 'as' => 'back.add-students']);

  Route::get('students-profile', ['uses' => 'BackViewController@students_profile', 'as' => 'back.students-profile']);

  Route::get('students-invoice', ['uses' => 'BackViewController@students_invoice', 'as' => 'back.students-invoice']);

  Route::get('professors', ['uses' => 'BackViewController@professors', 'as' => 'back.professors']);

  Route::get('add-staff', ['uses' => 'BackViewController@add_staff', 'as' => 'back.add-staff']);

  Route::get('add-professors', ['uses' => 'BackViewController@add_professors', 'as' => 'back.add-professors']);

  Route::get('sign-in', ['uses' => 'BackViewController@sign_in', 'as' => 'back.sign-in']);

  Route::get('sign-up', ['uses' => 'BackViewController@sign_up', 'as' => 'back.sign-up']);

  Route::get('forgot-password', ['uses' => 'BackViewController@forgot_password', 'as' => 'back.forgot-password']);

  Route::get('404', ['uses' => 'BackViewController@four_oh_four', 'as' => 'back.404']);

  Route::get('500', ['uses' => 'BackViewController@server_error', 'as' => 'back.500']);

  Route::get('page-offline', ['uses' => 'BackViewController@page_offline', 'as' => 'back.page-offline']);

  Route::get('locked', ['uses' => 'BackViewController@locked', 'as' => 'back.locked']);

  Route::get('events', ['uses' => 'BackViewController@events', 'as' => 'back.events']);

  Route::get('departments', ['uses' => 'BackViewController@departments', 'as' => 'back.departments']);

  Route::get('add-departments', ['uses' => 'BackViewController@add_departments', 'as' => 'back.add-departments']);

  Route::get('courses', ['uses' => 'BackViewController@courses', 'as' => 'back.courses']);

  Route::get('add-courses', ['uses' => 'BackViewController@add_courses', 'as' => 'back.add-courses']);

  Route::get('courses-info', ['uses' => 'BackViewController@courses_info', 'as' => 'back.courses-info']);

  Route::get('library', ['uses' => 'BackViewController@library', 'as' => 'back.library']);

  Route::get('classroom', ['uses' => 'BackViewController@classroom', 'as' => 'back.classroom']);

  Route::get('noticeboard', ['uses' => 'BackViewController@noticeboard', 'as' => 'back.noticeboard']);

  Route::get('centres', ['uses' => 'BackViewController@centres', 'as' => 'back.centres']);

  Route::get('blog-dashboard', ['uses' => 'BackViewController@blog_dashboard', 'as' => 'back.blog-dashboard']);

  Route::get('blog-post', ['uses' => 'BackViewController@blog_post', 'as' => 'back.blog-post']);

  Route::get('blog-list', ['uses' => 'BackViewController@blog_list', 'as' => 'back.blog-list']);

  Route::get('blog-grid', ['uses' => 'BackViewController@blog_grid', 'as' => 'back.blog-grid']);

  Route::get('blog-details', ['uses' => 'BackViewController@blog_details', 'as' => 'back.blog-details']);

  Route::get('file-dashboard', ['uses' => 'BackViewController@file_dashboard', 'as' => 'back.file-dashboard']);

  Route::get('file-documents', ['uses' => 'BackViewController@file_documents', 'as' => 'back.file-documents']);

  Route::get('file-media', ['uses' => 'BackViewController@file_media', 'as' => 'back.file-media']);

  Route::get('file-images', ['uses' => 'BackViewController@file_images', 'as' => 'back.file-images']);

  Route::get('mail-inbox', ['uses' => 'BackViewController@mail_inbox', 'as' => 'back.mail-inbox']);

  Route::get('chat', ['uses' => 'BackViewController@chat', 'as' => 'back.chat']);

  Route::get('contact', ['uses' => 'BackViewController@contact', 'as' => 'back.contact']);

  Route::get('widgets-app', ['uses' => 'BackViewController@widgets_app', 'as' => 'back.widgets-app']);

  Route::get('widgets-data', ['uses' => 'BackViewController@widgets_data', 'as' => 'back.widgets-data']);

  Route::get('blank', ['uses' => 'BackViewController@blank', 'as' => 'back.blank']);

  Route::get('dashboard-rtl', ['uses' => 'BackViewController@dashboard_rtl', 'as' => 'back.dashboard-rtl']);

  Route::get('index2', ['uses' => 'BackViewController@index2', 'as' => 'back.index2']);

  Route::get('image-gallery', ['uses' => 'BackViewController@image_gallery', 'as' => 'back.image-gallery']);

  Route::get('timeline', ['uses' => 'BackViewController@timeline', 'as' => 'back.timeline']);

  Route::get('invoice', ['uses' => 'BackViewController@invoice', 'as' => 'back.invoice']);

  Route::get('ui_kit', ['uses' => 'BackViewController@ui_kit', 'as' => 'back.ui_kit']);

  Route::get('alerts', ['uses' => 'BackViewController@alerts', 'as' => 'back.alerts']);

  Route::get('collapse', ['uses' => 'BackViewController@collapse', 'as' => 'back.collapse']);

  Route::get('colors', ['uses' => 'BackViewController@colors', 'as' => 'back.colors']);

  Route::get('dialogs', ['uses' => 'BackViewController@dialogs', 'as' => 'back.dialogs']);

  Route::get('icons', ['uses' => 'BackViewController@icons', 'as' => 'back.icons']);

  Route::get('list-group', ['uses' => 'BackViewController@list_group', 'as' => 'back.list-group']);

  Route::get('media-object', ['uses' => 'BackViewController@media_object', 'as' => 'back.media-object']);

  Route::get('modals', ['uses' => 'BackViewController@modals', 'as' => 'back.modals']);

  Route::get('notifications', ['uses' => 'BackViewController@notifications', 'as' => 'back.notifications']);

  Route::get('progressbars', ['uses' => 'BackViewController@progressbars', 'as' => 'back.progressbars']);

  Route::get('range-sliders', ['uses' => 'BackViewController@range_sliders', 'as' => 'back.range-sliders']);

  Route::get('sortable-nestable', ['uses' => 'BackViewController@sortable_nestable', 'as' => 'back.sortable-nestable']);

  Route::get('tabs', ['uses' => 'BackViewController@tabs', 'as' => 'back.tabs']);

  Route::get('waves', ['uses' => 'BackViewController@waves', 'as' => 'back.waves']);

  Route::get('profile', ['uses' => 'BackViewController@profile', 'as' => 'back.profile']);

  Route::get('parents', ['uses' => 'BackViewController@parents', 'as' => 'back.parents']);

  Route::get('search-results', ['uses' => 'BackViewController@search_results', 'as' => 'back.search-results']);

  Route::put('accept-by-staff-level-one/{folder}', ['uses' => 'FolderController@acceptByStaffLevelOne', 'as' => 'folder.accept.staff.one']);

  Route::put('reject-by-staff-level-one/{folder}', ['uses' => 'FolderController@rejectByStaffLevelOne', 'as' => 'folder.reject.staff.one']);

  Route::put('accept-by-staff-level-two/{folder}', ['uses' => 'FolderController@acceptByStaffLevelTwo', 'as' => 'folder.accept.staff.two']);

  Route::put('reject-by-staff-level-two/{folder}', ['uses' => 'FolderController@rejectByStaffLevelTwo', 'as' => 'folder.reject.staff.two']);

  Route::put('student-status/{student}', ['uses' => 'StudentController@updateStatus', 'as' => 'student.status']);

});

Route::resource('school', 'SchoolController');
Route::resource('training', 'TrainingController');
Route::resource('option', 'OptionController');

Route::post('registerstaff', 'Auth\RegisterController@registerStaff')->name('registerstaff');


Auth::routes(['verify' => true]);

// Auth::routes();

Route::get('/home', ['uses' => 'HomeController@index', 'as' => 'dashboard']);


Route::get('pursuit-registration/{step}', ['uses' => 'HomeController@pursuitRegistration', 'as' => 'register.pursuit'])->where('step', '[1-4]?');

Route::resource('user', 'UserController', ['except' => ['create', 'store']]);
Route::resource('student', 'StudentController');
Route::resource('folder', 'FolderController');
Route::get('admission', 'AdmissionPaymentController@create')->name('admission.create');
Route::post('admission', 'AdmissionPaymentController@store')->name('admission.store');

app/Models/Folder.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Folder extends Model
{
  protected $fillable = [
    'birthCertificate', 'nationalityCertificate', 'attestation', 'bulletin',
    'NICReference', 'picture', 'validateByStaffLevelOne',
    'validateByStaffLevelTwo', 'student_id',
  ];

  public function student()
  {
    return $this->belongsTo('App\Models\Student');
  }
}

app/Http/Controllers/FolderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\{
    FolderCreateRequest,
    FolderUpdateRequest,
    DecisionOnFolderRequest
};

use App\Management\PictureManagementInterface;

use App\Repositories\{
    FolderRepository,
    StudentRepository,
    UserRepository
};

use Illuminate\Support\Facades\Mail;

use App\Mail\FolderAccepted;

use App\Models\{
    User,
    Student
};

class FolderController extends Controller
{
    protected $folderRepository,
        $studentRepository,
        $userRepository;


    protected $pagination = 10;

    public function __construct(
        FolderRepository $folderRepository,
        StudentRepository $studentRepository,
        UserRepository $userRepository
    ) {
        $this->middleware('auth');
        $this->middleware('admin', ['only' => ['index', 'delete']]);
        $this->folderRepository = $folderRepository;
        $this->studentRepository = $studentRepository;
        $this->userRepository = $userRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $folders = $this->folderRepository->getWithStudentPaginate($this->pagination);
        $links = $folders->render();

        return view('back-end.folders.index', compact('folders', 'links'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $folder = $this->folderRepository->getById($id);

        return view('folders.show', compact('folder'));
    }

    /**
     * Show the form for creating the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $student_id = $this->studentRepository->getStudentByUserId(auth()->user()->id)->id;
        return view('folders.create', compact('student_id'));
    }

    /**
     * Create a new resource in storage.
     *
     * @param  \App\Http\Requests\FolderCreateRequest  $request
     * @param  \App\Management\PictureManagementInterface $manager
     * @return \Illuminate\Http\Response
     */
    public function store(FolderCreateRequest $request, PictureManagementInterface $manager)
    {
        $user_id = auth()->user()->id;
        $student = $this->studentRepository->getStudentByUserId($user_id);
        $student_folder = array(
            'id' => $student->id,
            'firstName' => $student->firstName,
            'lastName' => $student->lastName
        );

        if (($paths=$manager->save($student_folder, $request->allFiles()))!==false)
        {
            $paths = array_merge($paths, ['student_id' => $student->id]);
            $this->folderRepository->store($paths);
            $this->userRepository->update($user_id, ['step' => 3]);
            return redirect()->route('admission.create');
        }

        else {
            session()->put('image_error', 'Images invalides !');
            return redirect()->route('folder.create')->withInput();
        }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $folder = $this->folderRepository->getById($id);

      return view('folders.edit', compact('folder'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\FolderUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FolderUpdateRequest $request, $id)
    {
        $this->folderRepository->update($id, $request->allFiles());

        return redirect()->route('admission.create');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->folderRepository->delete($id);

        return back();
    }

    private function sendMail($folder_id)
    {
        $user = $this->folderRepository->getgetUserByFolderId($folder_id);
        $student = $this->folderRepository->getStudentByFolderId($folder_id);
        Mail::to($user->email)->send(new FolderAccepted($user, $student));
    }

    public function acceptByStaffLevelOne($id)
    {
      $result = $this->folderRepository->updateByStaff($id, 1, 'accept');
      if ($result['validateByAllStaff']) 
        $this->sendMail($id);
      return back();
    }

    public function rejectByStaffLevelOne($id)
    {
      $this->folderRepository->updateByStaff($id, 1, 'reject');
      return back();
    }

    public function acceptByStaffLevelTwo($id)
    {
      $result = $this->folderRepository->updateByStaff($id, 2, 'accept');
      if ($result['validateByAllStaff']) 
        $this->sendMail($id);
      return back();
    }

    public function rejectByStaffLevelTwo($id)
    {
      $this->folderRepository->updateByStaff($id, 2, 'reject');
      return back();
    }
}

resources/views/back-end/folders/index.blade.php
@extends('back-end.main-layout')

@section('content')
<br>
<section class="content">
  <div class="row justify-content-center">
    <div class="col-sm-10">
      <div class="card">
        <div class="card-header text-center bg-primary">
          <h3 class="card-title">Liste des dossiers en instance</h3>
          @if (Session::has('success'))
            <div class="alert alert-success text-center">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
              <p>{{ Session::get('success') }}</p>
            </div>
          @endif
        </div>
        <div class="card-body">
          <table class="table table-condensed table-bordered table-responsive table-hover">
    				<thead>
    					<tr>
    						<th>#</th>
    						<th>Nom</th>
                <th>Prénoms</th>
    						<th>Plus sur le postulant</th>
    						<th>Details du dossier</th>
    						<th>Action</th>
                @if(Auth::user()->rank === 1)
                  <th>Assigner Statut</th>
                @endif
    					</tr>
    				</thead>
    				<tbody>
    					@foreach ($folders as $folder)
    						<tr>
    							<td class="folder">{!! $folder->id !!}</td>
    							<td class="text-primary"><strong>{!! $folder->student->lastName !!}</strong></td>
                  <td class="text-primary"><strong>{!! $folder->student->firstName !!}</strong></td>
    							<td>{!! link_to_route('student.show', 'En savoir plus', [$folder->student_id], ['class' => 'btn btn-info btn-block']) !!}</td>
    							<td>{!! link_to_route('folder.show', 'Details dossier', [$folder->id], ['class' => 'btn btn-info btn-block']) !!}</td>
                  @if(Auth::user()->rank === 1 && ($folder->validateByStaffLevelOne==-1 || $folder->validateByStaffLevelOne== 0))
                    <td>
                      {!! Form::open(['method' => 'PUT', 'route' => ['folder.accept.staff.one', $folder->id]]) !!}
                        {!! Form::submit('Valider', ['class' => 'btn btn-success btn-block', 'onclick' => 'return confirm(\'Vraiment valider ce dossier ?\')']) !!}
                      {!! Form::close() !!}
                    </td>
                  @endif

                  @if(Auth::user()->rank === 1 && $folder->validateByStaffLevelOne==1)
                    <td>
                      {!! Form::open(['method' => 'PUT', 'route' => ['folder.reject.staff.one', $folder->id]]) !!}
                        {!! Form::submit('Rejeter', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Vraiment rejeter ce dossier ?\')']) !!}
                      {!! Form::close() !!}
                    </td>
                  @endif

                  @if(Auth::user()->rank === 2 && ($folder->validateByStaffLevelTwo==-1 || $folder->validateByStaffLevelTwo==0))
                    <td>
                      {!! Form::open(['method' => 'PUT', 'route' => ['folder.accept.staff.two', $folder->id]]) !!}
                        {!! Form::submit('Valider', ['class' => 'btn btn-success btn-block', 'onclick' => 'return confirm(\'Vraiment valider ce dossier ?\')']) !!}
                      {!! Form::close() !!}
                    </td>
                  @endif
                  @if(Auth::user()->rank === 2 && $folder->validateByStaffLevelTwo == 1)
                    <td>
                      {!! Form::open(['method' => 'PUT', 'route' => ['folder.reject.staff.two', $folder->id]]) !!}
                        {!! Form::submit('Rejeter', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Vraiment rejeter ce dossier ?\')']) !!}
                      {!! Form::close() !!}
                    </td>
                  @endif

                  @if(Auth::user()->rank === 1)
                    <td>
                      <button type="button" class="btn btn-info btn-block" data-toggle="collapse" data-target="#student_status_collapse{{$folder->id}}">Assignation</button>
                      <div id="student_status_collapse{{$folder->id}}" class="collapse">
                        <p class="text-center">Etudiant : <b>{{ $folder->student->lastName }}  {{ $folder->student->firstName }}</b></p>
                        {!! Form::open(['method' => 'PUT', 'route' => ['student.status', $folder->student_id]]) !!}
                          <div class="form-group">
                            <select name="status" required>
                              <option value="Boursier">Boursier</option>
                              <option value="Titre Payant">Titre Payant</option>
                              <option value="Sponsoring">Sponsoring</option>
                            </select>
                            @if ($errors->has('status'))
                              <span class="text-danger" role="alert">
                                <strong>{{ $errors->first('status') }}</strong>
                              </span>
                            @endif
                          </div><br>
                          {!! Form::submit('Assigner', ['class' => 'btn btn-primary btn-block', 'onclick' => 'return confirm(\'Vraiment attribuer ce statut ?\')']) !!}
                        {!! Form::close() !!}
                      </div>
                    </td>
                  @endif
    						</tr>
    					@endforeach
    	  			</tbody>
    			</table>
        </div>
      </div>
      {!! $links !!}
    </div>
    </div>
  </div>
</section>
@endsection