routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => 'FrontViewController@index', 'as' => 'front.home']);

Route::get('courses', ['uses' => 'FrontViewController@courses', 'as' => 'front.courses']);

Route::get('event', ['uses' => 'FrontViewController@event', 'as' => 'front.event']);

Route::get('teachers', ['uses' => 'FrontViewController@teachers', 'as' => 'front.teachers']);

Route::get('teachers-details', ['uses' => 'FrontViewController@teacher_detail', 'as' => 'front.teacher-details']);

Route::get('blog', ['uses' => 'FrontViewController@blog', 'as' => 'front.blog']);

Route::get('blog-details', ['uses' => 'FrontViewController@blog_details', 'as' => 'front.blog-detail']);

Route::get('about', ['uses' => 'FrontViewController@about', 'as' => 'front.about']);

Route::get('faq', ['uses' => 'FrontViewController@faq', 'as' => 'front.faq']);

Route::get('galary', ['uses' => 'FrontViewController@galary', 'as' => 'front.galary']);

Route::get('price', ['uses' => 'FrontViewController@price', 'as' => 'front.price']);

Route::get('contact', ['uses' => 'FrontViewController@contact', 'as' => 'front.contact']);


// Theme Forest Admin
Route::prefix('admin')->group(function () {
  Route::get('/', ['uses' => 'BackViewController@index', 'as' => 'back.home']);

  Route::get('students', ['uses' => 'BackViewController@students', 'as' => 'back.students']);

  Route::get('add-students', ['uses' => 'BackViewController@add_students', 'as' => 'back.add-students']);

  Route::get('students-profile', ['uses' => 'BackViewController@students_profile', 'as' => 'back.students-profile']);

  Route::get('students-invoice', ['uses' => 'BackViewController@students_invoice', 'as' => 'back.students-invoice']);

  Route::get('professors', ['uses' => 'BackViewController@professors', 'as' => 'back.professors']);

  Route::get('add-staff', ['uses' => 'BackViewController@add_staff', 'as' => 'back.add-staff']);

  Route::get('add-professors', ['uses' => 'BackViewController@add_professors', 'as' => 'back.add-professors']);

  Route::get('sign-in', ['uses' => 'BackViewController@sign_in', 'as' => 'back.sign-in']);

  Route::get('sign-up', ['uses' => 'BackViewController@sign_up', 'as' => 'back.sign-up']);

  Route::get('forgot-password', ['uses' => 'BackViewController@forgot_password', 'as' => 'back.forgot-password']);

  Route::get('404', ['uses' => 'BackViewController@four_oh_four', 'as' => 'back.404']);

  Route::get('500', ['uses' => 'BackViewController@server_error', 'as' => 'back.500']);

  Route::get('page-offline', ['uses' => 'BackViewController@page_offline', 'as' => 'back.page-offline']);

  Route::get('locked', ['uses' => 'BackViewController@locked', 'as' => 'back.locked']);

  Route::get('events', ['uses' => 'BackViewController@events', 'as' => 'back.events']);

  Route::get('departments', ['uses' => 'BackViewController@departments', 'as' => 'back.departments']);

  Route::get('add-departments', ['uses' => 'BackViewController@add_departments', 'as' => 'back.add-departments']);

  Route::get('courses', ['uses' => 'BackViewController@courses', 'as' => 'back.courses']);

  Route::get('add-courses', ['uses' => 'BackViewController@add_courses', 'as' => 'back.add-courses']);

  Route::get('courses-info', ['uses' => 'BackViewController@courses_info', 'as' => 'back.courses-info']);

  Route::get('library', ['uses' => 'BackViewController@library', 'as' => 'back.library']);

  Route::get('classroom', ['uses' => 'BackViewController@classroom', 'as' => 'back.classroom']);

  Route::get('noticeboard', ['uses' => 'BackViewController@noticeboard', 'as' => 'back.noticeboard']);

  Route::get('centres', ['uses' => 'BackViewController@centres', 'as' => 'back.centres']);

  Route::get('blog-dashboard', ['uses' => 'BackViewController@blog_dashboard', 'as' => 'back.blog-dashboard']);

  Route::get('blog-post', ['uses' => 'BackViewController@blog_post', 'as' => 'back.blog-post']);

  Route::get('blog-list', ['uses' => 'BackViewController@blog_list', 'as' => 'back.blog-list']);

  Route::get('blog-grid', ['uses' => 'BackViewController@blog_grid', 'as' => 'back.blog-grid']);

  Route::get('blog-details', ['uses' => 'BackViewController@blog_details', 'as' => 'back.blog-details']);

  Route::get('file-dashboard', ['uses' => 'BackViewController@file_dashboard', 'as' => 'back.file-dashboard']);

  Route::get('file-documents', ['uses' => 'BackViewController@file_documents', 'as' => 'back.file-documents']);

  Route::get('file-media', ['uses' => 'BackViewController@file_media', 'as' => 'back.file-media']);

  Route::get('file-images', ['uses' => 'BackViewController@file_images', 'as' => 'back.file-images']);

  Route::get('mail-inbox', ['uses' => 'BackViewController@mail_inbox', 'as' => 'back.mail-inbox']);

  Route::get('chat', ['uses' => 'BackViewController@chat', 'as' => 'back.chat']);

  Route::get('contact', ['uses' => 'BackViewController@contact', 'as' => 'back.contact']);

  Route::get('widgets-app', ['uses' => 'BackViewController@widgets_app', 'as' => 'back.widgets-app']);

  Route::get('widgets-data', ['uses' => 'BackViewController@widgets_data', 'as' => 'back.widgets-data']);

  Route::get('blank', ['uses' => 'BackViewController@blank', 'as' => 'back.blank']);

  Route::get('dashboard-rtl', ['uses' => 'BackViewController@dashboard_rtl', 'as' => 'back.dashboard-rtl']);

  Route::get('index2', ['uses' => 'BackViewController@index2', 'as' => 'back.index2']);

  Route::get('image-gallery', ['uses' => 'BackViewController@image_gallery', 'as' => 'back.image-gallery']);

  Route::get('timeline', ['uses' => 'BackViewController@timeline', 'as' => 'back.timeline']);

  Route::get('invoice', ['uses' => 'BackViewController@invoice', 'as' => 'back.invoice']);

  Route::get('ui_kit', ['uses' => 'BackViewController@ui_kit', 'as' => 'back.ui_kit']);

  Route::get('alerts', ['uses' => 'BackViewController@alerts', 'as' => 'back.alerts']);

  Route::get('collapse', ['uses' => 'BackViewController@collapse', 'as' => 'back.collapse']);

  Route::get('colors', ['uses' => 'BackViewController@colors', 'as' => 'back.colors']);

  Route::get('dialogs', ['uses' => 'BackViewController@dialogs', 'as' => 'back.dialogs']);

  Route::get('icons', ['uses' => 'BackViewController@icons', 'as' => 'back.icons']);

  Route::get('list-group', ['uses' => 'BackViewController@list_group', 'as' => 'back.list-group']);

  Route::get('media-object', ['uses' => 'BackViewController@media_object', 'as' => 'back.media-object']);

  Route::get('modals', ['uses' => 'BackViewController@modals', 'as' => 'back.modals']);

  Route::get('notifications', ['uses' => 'BackViewController@notifications', 'as' => 'back.notifications']);

  Route::get('progressbars', ['uses' => 'BackViewController@progressbars', 'as' => 'back.progressbars']);

  Route::get('range-sliders', ['uses' => 'BackViewController@range_sliders', 'as' => 'back.range-sliders']);

  Route::get('sortable-nestable', ['uses' => 'BackViewController@sortable_nestable', 'as' => 'back.sortable-nestable']);

  Route::get('tabs', ['uses' => 'BackViewController@tabs', 'as' => 'back.tabs']);

  Route::get('waves', ['uses' => 'BackViewController@waves', 'as' => 'back.waves']);

  Route::get('profile', ['uses' => 'BackViewController@profile', 'as' => 'back.profile']);

  Route::get('parents', ['uses' => 'BackViewController@parents', 'as' => 'back.parents']);

  Route::get('search-results', ['uses' => 'BackViewController@search_results', 'as' => 'back.search-results']);

  Route::put('accept-by-staff-level-one/{folder}', ['uses' => 'FolderController@acceptByStaffLevelOne', 'as' => 'folder.accept.staff.one']);

  Route::put('reject-by-staff-level-one/{folder}', ['uses' => 'FolderController@rejectByStaffLevelOne', 'as' => 'folder.reject.staff.one']);

  Route::put('accept-by-staff-level-two/{folder}', ['uses' => 'FolderController@acceptByStaffLevelTwo', 'as' => 'folder.accept.staff.two']);

  Route::put('reject-by-staff-level-two/{folder}', ['uses' => 'FolderController@rejectByStaffLevelTwo', 'as' => 'folder.reject.staff.two']);

  Route::put('student-status/{student}', ['uses' => 'StudentController@updateStatus', 'as' => 'student.status']);

});

Route::resource('school', 'SchoolController');
Route::resource('training', 'TrainingController');
Route::resource('option', 'OptionController');

Route::post('registerstaff', 'Auth\RegisterController@registerStaff')->name('registerstaff');


Auth::routes(['verify' => true]);

// Auth::routes();

Route::get('/home', ['uses' => 'HomeController@index', 'as' => 'dashboard']);


Route::get('pursuit-registration/{step}', ['uses' => 'HomeController@pursuitRegistration', 'as' => 'register.pursuit'])->where('step', '[1-4]?');

Route::resource('user', 'UserController', ['except' => ['create', 'store']]);
Route::resource('student', 'StudentController');
Route::resource('folder', 'FolderController');
Route::get('admission', 'AdmissionPaymentController@create')->name('admission.create');
Route::post('admission', 'AdmissionPaymentController@store')->name('admission.store');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
  protected $fillable = [
    'firstName', 'lastName', 'birthday', 'placeOfBirth', 'phone',
    'sex', 'country', 'province', 'city', 'user_id'
  ];

  public function user()
  {
    return $this->belongsTo('App\Models\User');
  }

  public function folder()
  {
    return $this->hasOne('App\Models\Folder');
  }

  public function trainings()
  {
    return $this->belongsToMany('App\Models\Training');
  }

  public function schoolFees()
  {
    return $this->hasMany('App\Models\schoolFee');
  }

  public function parents()
  {
    return $this->hasMany('App\Models\Parent');
  }

}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\{
    StudentCreateRequest,
    StudentUpdateRequest,
    StudentStatusRequest
};

use Carbon\Carbon;

use App\Repositories\{
    StudentRepository,
    TrainingRepository,
    UserRepository
};

use Illuminate\{
  Support\Facades\DB
};

class StudentController extends Controller
{
    protected $studentRepository,
        $userRepository,
        $trainingRepository;

    protected $pagination = 10;

    public function __construct(
        StudentRepository $studentRepository,
        UserRepository $userRepository,
        TrainingRepository $trainingRepository
    )
    {
      $this->middleware('auth');
      $this->middleware('admin', ['only' => ['index', 'delete']]);

      $this->studentRepository = $studentRepository;
      $this->userRepository = $userRepository;
      $this->trainingRepository = $trainingRepository;

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = $this->studentRepository->getWithUserFolderAndTrainingsPaginate($this->pagination);
        $links = $students->render();

        return view('back-end.students.index', compact('students', 'links'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $student = $this->studentRepository->getById($id);
        $schoolFee = DB::table('school_fees')->where([['student_id', '=', $id], ['type', '=', 'Admission']])->first();

        return view('students.show', compact('student', 'schoolFee'));
    }

    /**
     * Show the form for creating the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $trainings = $this->trainingRepository->getTrainings();

        return view('students.create', compact('trainings'));
    }

    /**
     * Create the specified resource in storage.
     *
     * @param  \App\Http\Requests\StudentCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentCreateRequest $request)
    {
        $user_id = auth()->user()->id;
        $request->merge(['user_id' => $user_id]);

        $student = $this->studentRepository->store($request->except(['training_id', 'cycle']));

        DB::table('student_training')->insert([
            'student_id' => $student->id,
            'training_id' => $request->input('training_id'),
            'dateOfRegistration' => Carbon::now(),
            'semester'=> null,
            'cycle' => $request->input('cycle')
        ]);

        $this->userRepository->update($user_id, ['step' => 2]);

        return redirect()->route('folder.create');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $student = $this->studentRepository->getById($id);
      $trainings = $this->trainingRepository->getTrainings();

      return view('students.edit', compact('student', 'trainings'));
    }



    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\StudentUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StudentUpdateRequest $request, $id)
    {
        $this->studentRepository->update($id, $request->except(['training_id', 'cycle']));

        DB::table('student_training') ->where(
            'student_id', $this->studentRepository->getStudentByUserId(auth()->user()->id)->id
        )->update([
            'training_id' => $request->input('training_id'),
            'cycle' => $request->input('cycle')
        ]);

        return redirect()->route('folder.create');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->studentRepository->delete($id);

        return back();
    }

    public function updateStatus($id, StudentStatusRequest $request)
    {
      $this->studentRepository->update($id, ['status' => $request->status]);
      $student = $this->studentRepository->getById($id);
      return back()->with(['success' => 'Le statut de '.$request->status.' a été attribué à l\'étudiant '.$student->firstName.' '.$student->lastName]);
    }
}

resources/views/students/create.blade.php
@extends('front-end.layout')

@section('content')
    <form method="POST" action="{{ route('student.store') }}" aria-label="{{ __('Informations Générales') }}">
        @csrf

        <fieldset>
            <legend class="text-center">Cycle et Filière</legend>
            <div class="form-group row">
                <label for="training" class="col-md-4 col-form-label text-md-right">{{ __('Filière') }}</label>
                <div class="col-md-6">
                    <select class="form-control {{ $errors->has('training_id') ? 'is-invalid' : '' }}" name="training_id" id="training" value="{{ old('training_id') }}" required>
                        @foreach ($trainings as $training)
                            <option value="{{$training->id}}">{{$training->name}}</option>
                        @endforeach
                    </select>
                    @if ($errors->has('training_id'))
                        <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('training_id') }}</strong>
            </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="cycle" class="col-md-4 col-form-label text-md-right">{{ __('Cycle') }}</label>
                <div class="col-md-6">
                    <select class="form-control {{ $errors->has('cycle') ? 'is-invalid' : '' }}" name="cycle" id="cycle" value="{{ old('cycle') }}" required>
                        <option value="Licence">Licence</option>
                        <option value="Ingénieur">Ingénieur</option>
                        <option value="Master">Master</option>
                        <option value="Doctorat">Doctorat</option>
                    </select>
                    @if ($errors->has('cycle'))
                        <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('cycle') }}</strong>
              </span>
                    @endif
                </div>
            </div>
        </fieldset>

        <fieldset>
            <legend class="text-center">Informations Générales</legend>
            <div class="form-group row">
                <label for="lastName" class="col-md-4 col-form-label text-md-right">{{ __('Nom :* ') }}</label>
                <div class="col-md-6">
                    <input type="lastName" name="lastName" class="form-control{{ $errors->has('lastName') ? ' is-invalid' : '' }}" id="lastName" value="{{ old('lastName') }}" required >
                    @if ($errors->has('lastName'))
                        <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('lastName') }}</strong>
            </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="firstName" class="col-md-4 col-form-label text-md-right">{{ __('Prénoms :* ') }}</label>
                <div class="col-md-6">
                    <input type="text" name="firstName" class="form-control{{ $errors->has('firstName') ? ' is-invalid' : '' }}" id="firstName" value="{{ old('firstName') }}" required >
                    @if ($errors->has('firstName'))
                        <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('firstName') }}</strong>
            </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="sex" class="col-md-4 col-form-label text-md-right">{{ __('Sexe') }}</label>
                <div class="col-md-6">
                    <select class="form-control{{ $errors->has('sex') ? ' is-invalid' : ''}}" name="sex" id="sex" required>
                        <option value="Masculin">Masculin</option>
                        <option value="Féminin">Féminin</option>
                        <option value="Autre">Autre</option>
                    </select>
                    @if ($errors->has('sex'))
                        <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('sex') }}</strong>
            </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="birthday" class="col-md-4 col-form-label text-md-right">{{ __('Date de naissance :* ') }}</label>

                <div class="col-md-6">
                    <input type="date" name="birthday" class="form-control{{ $errors->has('birthday') ? ' is-invalid' : '' }}" id="birthday" value="{{ old('birthday') }}" required >
                    @if ($errors->has('birthday'))
                        <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('birthday') }}</strong>
            </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="placeOfBirth" class="col-md-4 col-form-label text-md-right">{{ __('Lieu de naissance :* ') }}</label>
                <div class="col-md-6">
                    <input type="text" name="placeOfBirth" class="form-control{{ $errors->has('placeOfBirth') ? ' is-invalid' : '' }}" id="placeOfBirth" value="{{ old('placeOfBirth') }}" required >
                    @if ($errors->has('placeOfBirth'))
                        <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('placeOfBirth') }}</strong>
            </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Téléphone :* ') }}</label>
                <div class="col-md-6">
                    <input type="tel" name="phone" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" id="phone" value="{{ old('phone') }}" required >
                    @if ($errors->has('phone'))
                        <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('phone') }}</strong>
            </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="country" class="col-md-4 col-form-label text-md-right">{{ __('Pays :* ') }}</label>
                <div class="col-md-6">
                    <select name="country" id="country" class="form-control{{ $errors->has('country') ? ' is-invalid' : ''}}" required>
                        <option value="Bénin">Bénin</option>
                        <option value="Mali">Mali</option>
                    </select>
                    @if ($errors->has('country'))
                        <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('country') }}</strong>
            </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="province" class="col-md-4 col-form-label text-md-right">{{ __('Département') }}</label>
                <div class="col-md-6">
                    <input type="text" name="province" class="form-control{{ $errors->has('province') ? ' is-invalid' : '' }}" id="province" value="{{ old('province') }}" required >
                    @if ($errors->has('province'))
                        <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('province') }}</strong>
            </span>
                    @endif
                </div>
            </div>

            <div class="form-group row">
                <label for="city" class="col-md-4 col-form-label text-md-right">{{ __('Ville :* ') }}</label>
                <div class="col-md-6">
                    <input type="text" name="city" class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" id="city" value="{{ old('city') }}" required >
                    @if ($errors->has('city'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('city') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <button type="submit" class="btn btn-primary col-md-1 offset-md-5">
                    Suivant
                </button>
            </div>
        </fieldset>
    </form>
@endsection

resources/views/students/edit.blade.php
@extends('front-end.layout')

@section('styles')
  <style>
    .card-body {
      padding: 2%;
    }
  </style>
@endsection

@section('content')
  <br>
  <div class="container">
    <section class="row justify-content-center">
      <div class="col-sm-8">
        <div class="card">
          <div class="card-header bg-primary">Modification d'un étudiant</div>
          <div class="card-body">
            {!! Form::model($student, ['route' => ['student.update', $student->id], 'method' => 'put', 'class' => 'form-horizontal']) !!}
              <fieldset>
                  <legend class="text-center">Cycle et Filière</legend>
                  <div class="form-group row">
                      <label for="training" class="col-md-4 col-form-label text-md-right">{{ __('Filière') }}</label>
                      <div class="col-md-6">
                          <select class="form-control {{ $errors->has('training_id') ? 'is-invalid' : '' }}" name="training_id" id="training" value="{{ old('training_id') }}" required>
                              @foreach ($trainings as $training)
                                  <option value="{{$training->id}}">{{$training->name}}</option>
                              @endforeach
                          </select>
                          @if ($errors->has('training_id'))
                              <span class="invalid-feedback" role="alert">
              <strong>{{ $errors->first('training_id') }}</strong>
            </span>
                          @endif
                      </div>
                  </div>

                  <div class="form-group row">
                      <label for="cycle" class="col-md-4 col-form-label text-md-right">{{ __('Cycle') }}</label>
                      <div class="col-md-6">
                          <select class="form-control {{ $errors->has('cycle') ? 'is-invalid' : '' }}" name="cycle" id="cycle" value="{{ old('cycle') }}" required>
                              <option value="Licence">Licence</option>
                              <option value="Ingénieur">Ingénieur</option>
                              <option value="Master">Master</option>
                              <option value="Doctorat">Doctorat</option>
                          </select>
                          @if ($errors->has('cycle'))
                              <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('cycle') }}</strong>
              </span>
                          @endif
                      </div>
                  </div>
              </fieldset>
              <fieldset>
                  <legend>Informations Générales</legend>
                  <div class="form-group {!! $errors->has('lastName') ? 'has-error' : '' !!}">
                      {!! Form::text('lastName', null, ['class' => 'form-control text-center', 'placeholder' => 'Nom']) !!}
                      {!! $errors->first('lastName', '<small class="help-block">:message</small>') !!}
                  </div>

                  <div class="form-group {!! $errors->has('firstName') ? 'has-error' : '' !!}">
                      {!! Form::text('firstName', null, ['class' => 'form-control text-center', 'placeholder' => 'Prénoms']) !!}
                      {!! $errors->first('firstName', '<small class="help-block">:message</small>') !!}
                  </div>

                  <div class="form-group {!! $errors->has('sex') ? 'has-error' : '' !!}">
                      {!! Form::select('sex', ['Masculin' => 'Masculin', 'Féminin' => 'Féminin',
                          'Autres' => 'Autres'], null, ['class' => 'form-control text-center', 'placeholder' => 'Sexe']) !!}
                      {!! $errors->first('sex', '<small class="help-block">:message</small>') !!}
                  </div>

                  <div class="form-group {!! $errors->has('birthday') ? 'has-error' : '' !!}">
                      {!! Form::date('birthday', null, ['class' => 'form-control text-center', 'placeholder' => 'Date de naissance']) !!}
                      {!! $errors->first('birthday', '<small class="help-block">:message</small>') !!}
                  </div>

                  <div class="form-group {!! $errors->has('placeOfBirth') ? 'has-error' : '' !!}">
                      {!! Form::text('placeOfBirth', null, ['class' => 'form-control text-center', 'placeholder' => 'Lieu de naissance']) !!}
                      {!! $errors->first('placeOfBirth', '<small class="help-block">:message</small>') !!}
                  </div>

                  <div class="form-group {!! $errors->has('phone') ? 'has-error' : '' !!}">
                      {!! Form::text('phone', null, ['class' => 'form-control text-center', 'placeholder' => 'Téléphone']) !!}
                      {!! $errors->first('phone', '<small class="help-block">:message</small>') !!}
                  </div>

                  <div class="form-group {!! $errors->has('country') ? 'has-error' : '' !!}">
                      {!! Form::select('country', ['Bénin' => 'Bénin', 'Mali' => 'Mali',
                          'Sénégal' => 'Sénégal'], null, ['class' => 'form-control text-center', 'placeholder' => 'Pays']) !!}
                      {!! $errors->first('country', '<small class="help-block">:message</small>') !!}
                  </div>

                  <div class="form-group {!! $errors->has('province') ? 'has-error' : '' !!}">
                      {!! Form::text('province', null, ['class' => 'form-control text-center', 'placeholder' => 'Département']) !!}
                      {!! $errors->first('province', '<small class="help-block">:message</small>') !!}
                  </div>

                  <div class="form-group {!! $errors->has('city') ? 'has-error' : '' !!}">
                      {!! Form::text('city', null, ['class' => 'form-control text-center', 'placeholder' => 'Ville']) !!}
                      {!! $errors->first('city', '<small class="help-block">:message</small>') !!}
                  </div>

                  <div class="col-sm-3">
                      {!! Form::submit('Envoyer', ['class' => 'btn btn-primary ']) !!}
                  </div>
              </fieldset>
      			{!! Form::close() !!}
      		</div>
      	</div>
      </div>
    </section>
  </div>
@endsection

resources/views/students/show.blade.php
@extends('front-end.layout')

@section('content')
<br>
<section>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-6">
        <div class="card text-center">
          <div class="card-header bg-primary">Informations Générales sur {{ $student->firstName }}  {{ $student->lastName }}</div>
          <div class="card-body">
            <p>Prénoms : {{ $student->firstName }}</p>
            <p>Nom : {{ $student->lastName }}</p>
            <p>Date de naissance : {{ $student->birthday }}</p>
            <p>Lieu de naissance : {{ $student->placeOfBirth }}</p>
            <p>Numéro de Téléphone : {{ $student->phone }}</p>
            <p>Sexe : {{ $student->sex }}</p>
            <p>Pays : {{ $student->country }}</p>
            <p>Département : {{ $student->province }}</p>
            <p>Ville : {{ $student->city }}</p>
            @foreach ($student->trainings as $training)
              <p>Filière (s) : {{ $training->name }}</p>
              <p>Frais d'admission : ${{ $training->admissionFees }}USD</p>
            @endforeach

            @isset($schoolFee)
              <fieldset>
                <legend> Informations de paiement de frais d'admission</legend>
                <div class="row">
                    <h5 class="col-md-5 text-md-right">Type de paiement : </h5>
                    <h5 class="col-md-6">{{ $schoolFee->type }}</h5>
                </div>
                <div class="row">
                    <h5 class="col-md-5 text-md-right">Montant Payé : </h5>
                    <h5 class="col-md-6">${{ $schoolFee->pay }}USD</h5>
                </div>
                <div class="row">
                    <h5 class="col-md-5 text-md-right">Montant restant à payer : </h5>
                    <h5 class="col-md-6">${{ $schoolFee->letToPay }}USD</h5>
                </div>
              </fieldset>
            @endisset
          <div class="card-footer">
            <a href="javascript:history.back()" class="btn btn-primary">
              <span class="glyphicon glyphicon-circle-arrow-left"></span> Retour
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection