routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => 'FrontViewController@index', 'as' => 'front.home']);

Route::get('courses', ['uses' => 'FrontViewController@courses', 'as' => 'front.courses']);

Route::get('event', ['uses' => 'FrontViewController@event', 'as' => 'front.event']);

Route::get('teachers', ['uses' => 'FrontViewController@teachers', 'as' => 'front.teachers']);

Route::get('teachers-details', ['uses' => 'FrontViewController@teacher_detail', 'as' => 'front.teacher-details']);

Route::get('blog', ['uses' => 'FrontViewController@blog', 'as' => 'front.blog']);

Route::get('blog-details', ['uses' => 'FrontViewController@blog_details', 'as' => 'front.blog-detail']);

Route::get('about', ['uses' => 'FrontViewController@about', 'as' => 'front.about']);

Route::get('faq', ['uses' => 'FrontViewController@faq', 'as' => 'front.faq']);

Route::get('galary', ['uses' => 'FrontViewController@galary', 'as' => 'front.galary']);

Route::get('price', ['uses' => 'FrontViewController@price', 'as' => 'front.price']);

Route::get('contact', ['uses' => 'FrontViewController@contact', 'as' => 'front.contact']);


// Theme Forest Admin
Route::prefix('admin')->group(function () {
  Route::get('/', ['uses' => 'BackViewController@index', 'as' => 'back.home']);

  Route::get('students', ['uses' => 'BackViewController@students', 'as' => 'back.students']);

  Route::get('add-students', ['uses' => 'BackViewController@add_students', 'as' => 'back.add-students']);

  Route::get('students-profile', ['uses' => 'BackViewController@students_profile', 'as' => 'back.students-profile']);

  Route::get('students-invoice', ['uses' => 'BackViewController@students_invoice', 'as' => 'back.students-invoice']);

  Route::get('professors', ['uses' => 'BackViewController@professors', 'as' => 'back.professors']);

  Route::get('add-staff', ['uses' => 'BackViewController@add_staff', 'as' => 'back.add-staff']);

  Route::get('add-professors', ['uses' => 'BackViewController@add_professors', 'as' => 'back.add-professors']);

  Route::get('sign-in', ['uses' => 'BackViewController@sign_in', 'as' => 'back.sign-in']);

  Route::get('sign-up', ['uses' => 'BackViewController@sign_up', 'as' => 'back.sign-up']);

  Route::get('forgot-password', ['uses' => 'BackViewController@forgot_password', 'as' => 'back.forgot-password']);

  Route::get('404', ['uses' => 'BackViewController@four_oh_four', 'as' => 'back.404']);

  Route::get('500', ['uses' => 'BackViewController@server_error', 'as' => 'back.500']);

  Route::get('page-offline', ['uses' => 'BackViewController@page_offline', 'as' => 'back.page-offline']);

  Route::get('locked', ['uses' => 'BackViewController@locked', 'as' => 'back.locked']);

  Route::get('events', ['uses' => 'BackViewController@events', 'as' => 'back.events']);

  Route::get('departments', ['uses' => 'BackViewController@departments', 'as' => 'back.departments']);

  Route::get('add-departments', ['uses' => 'BackViewController@add_departments', 'as' => 'back.add-departments']);

  Route::get('courses', ['uses' => 'BackViewController@courses', 'as' => 'back.courses']);

  Route::get('add-courses', ['uses' => 'BackViewController@add_courses', 'as' => 'back.add-courses']);

  Route::get('courses-info', ['uses' => 'BackViewController@courses_info', 'as' => 'back.courses-info']);

  Route::get('library', ['uses' => 'BackViewController@library', 'as' => 'back.library']);

  Route::get('classroom', ['uses' => 'BackViewController@classroom', 'as' => 'back.classroom']);

  Route::get('noticeboard', ['uses' => 'BackViewController@noticeboard', 'as' => 'back.noticeboard']);

  Route::get('centres', ['uses' => 'BackViewController@centres', 'as' => 'back.centres']);

  Route::get('blog-dashboard', ['uses' => 'BackViewController@blog_dashboard', 'as' => 'back.blog-dashboard']);

  Route::get('blog-post', ['uses' => 'BackViewController@blog_post', 'as' => 'back.blog-post']);

  Route::get('blog-list', ['uses' => 'BackViewController@blog_list', 'as' => 'back.blog-list']);

  Route::get('blog-grid', ['uses' => 'BackViewController@blog_grid', 'as' => 'back.blog-grid']);

  Route::get('blog-details', ['uses' => 'BackViewController@blog_details', 'as' => 'back.blog-details']);

  Route::get('file-dashboard', ['uses' => 'BackViewController@file_dashboard', 'as' => 'back.file-dashboard']);

  Route::get('file-documents', ['uses' => 'BackViewController@file_documents', 'as' => 'back.file-documents']);

  Route::get('file-media', ['uses' => 'BackViewController@file_media', 'as' => 'back.file-media']);

  Route::get('file-images', ['uses' => 'BackViewController@file_images', 'as' => 'back.file-images']);

  Route::get('mail-inbox', ['uses' => 'BackViewController@mail_inbox', 'as' => 'back.mail-inbox']);

  Route::get('chat', ['uses' => 'BackViewController@chat', 'as' => 'back.chat']);

  Route::get('contact', ['uses' => 'BackViewController@contact', 'as' => 'back.contact']);

  Route::get('widgets-app', ['uses' => 'BackViewController@widgets_app', 'as' => 'back.widgets-app']);

  Route::get('widgets-data', ['uses' => 'BackViewController@widgets_data', 'as' => 'back.widgets-data']);

  Route::get('blank', ['uses' => 'BackViewController@blank', 'as' => 'back.blank']);

  Route::get('dashboard-rtl', ['uses' => 'BackViewController@dashboard_rtl', 'as' => 'back.dashboard-rtl']);

  Route::get('index2', ['uses' => 'BackViewController@index2', 'as' => 'back.index2']);

  Route::get('image-gallery', ['uses' => 'BackViewController@image_gallery', 'as' => 'back.image-gallery']);

  Route::get('timeline', ['uses' => 'BackViewController@timeline', 'as' => 'back.timeline']);

  Route::get('invoice', ['uses' => 'BackViewController@invoice', 'as' => 'back.invoice']);

  Route::get('ui_kit', ['uses' => 'BackViewController@ui_kit', 'as' => 'back.ui_kit']);

  Route::get('alerts', ['uses' => 'BackViewController@alerts', 'as' => 'back.alerts']);

  Route::get('collapse', ['uses' => 'BackViewController@collapse', 'as' => 'back.collapse']);

  Route::get('colors', ['uses' => 'BackViewController@colors', 'as' => 'back.colors']);

  Route::get('dialogs', ['uses' => 'BackViewController@dialogs', 'as' => 'back.dialogs']);

  Route::get('icons', ['uses' => 'BackViewController@icons', 'as' => 'back.icons']);

  Route::get('list-group', ['uses' => 'BackViewController@list_group', 'as' => 'back.list-group']);

  Route::get('media-object', ['uses' => 'BackViewController@media_object', 'as' => 'back.media-object']);

  Route::get('modals', ['uses' => 'BackViewController@modals', 'as' => 'back.modals']);

  Route::get('notifications', ['uses' => 'BackViewController@notifications', 'as' => 'back.notifications']);

  Route::get('progressbars', ['uses' => 'BackViewController@progressbars', 'as' => 'back.progressbars']);

  Route::get('range-sliders', ['uses' => 'BackViewController@range_sliders', 'as' => 'back.range-sliders']);

  Route::get('sortable-nestable', ['uses' => 'BackViewController@sortable_nestable', 'as' => 'back.sortable-nestable']);

  Route::get('tabs', ['uses' => 'BackViewController@tabs', 'as' => 'back.tabs']);

  Route::get('waves', ['uses' => 'BackViewController@waves', 'as' => 'back.waves']);

  Route::get('profile', ['uses' => 'BackViewController@profile', 'as' => 'back.profile']);

  Route::get('parents', ['uses' => 'BackViewController@parents', 'as' => 'back.parents']);

  Route::get('search-results', ['uses' => 'BackViewController@search_results', 'as' => 'back.search-results']);

  Route::put('accept-by-staff-level-one/{folder}', ['uses' => 'FolderController@acceptByStaffLevelOne', 'as' => 'folder.accept.staff.one']);

  Route::put('reject-by-staff-level-one/{folder}', ['uses' => 'FolderController@rejectByStaffLevelOne', 'as' => 'folder.reject.staff.one']);

  Route::put('accept-by-staff-level-two/{folder}', ['uses' => 'FolderController@acceptByStaffLevelTwo', 'as' => 'folder.accept.staff.two']);

  Route::put('reject-by-staff-level-two/{folder}', ['uses' => 'FolderController@rejectByStaffLevelTwo', 'as' => 'folder.reject.staff.two']);

  Route::put('student-status/{student}', ['uses' => 'StudentController@updateStatus', 'as' => 'student.status']);

});

Route::resource('school', 'SchoolController');
Route::resource('training', 'TrainingController');
Route::resource('option', 'OptionController');

Route::post('registerstaff', 'Auth\RegisterController@registerStaff')->name('registerstaff');


Auth::routes(['verify' => true]);

// Auth::routes();

Route::get('/home', ['uses' => 'HomeController@index', 'as' => 'dashboard']);


Route::get('pursuit-registration/{step}', ['uses' => 'HomeController@pursuitRegistration', 'as' => 'register.pursuit'])->where('step', '[1-4]?');

Route::resource('user', 'UserController', ['except' => ['create', 'store']]);
Route::resource('student', 'StudentController');
Route::resource('folder', 'FolderController');
Route::get('admission', 'AdmissionPaymentController@create')->name('admission.create');
Route::post('admission', 'AdmissionPaymentController@store')->name('admission.store');

app/Models/Training.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Training extends Model
{
  protected $fillable = [
    'code', 'name', 'description', 'fees', 'admissionFees', 'avatar', 'school_id'
  ];

  public function options()
  {
    return $this->hasMany('App\Models\Option');
  }

  public function school()
  {
    return $this->belongsTo('App\Models\School');
  }

  public function students()
  {
    return $this->belongsToMany('App\Models\Student');
  }
}

app/Http/Controllers/TrainingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\TrainingRequest;
use App\Management\PictureManagement;
use App\Repositories\{
    TrainingRepository,
    SchoolRepository
};

class TrainingController extends Controller
{
    protected $pagination = 5, $trainingRepository, $schoolRepository;

    public function __construct(TrainingRepository $trainingRepository, SchoolRepository $schoolRepository)
    {
      $this->middleware('auth');
      $this->middleware('admin', ['except' => ['index', 'show']]);

      $this->trainingRepository = $trainingRepository;
      $this->schoolRepository = $schoolRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $trainings = $this->trainingRepository->getPaginate($this->pagination);
        $links = $trainings->render();

        return view('trainings.index', compact('trainings', 'links'));   
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $schools = $this->schoolRepository->getAll();
        return view('trainings.create', compact('schools'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\TrainingRequest  $request
     * @param  App\Management\PictureManagement $pictureManager
     * @return \Illuminate\Http\Response
     */
    public function store(TrainingRequest $request, PictureManagement $pictureManager)
    {
        $data = $request->except('avatar');
        $path = $pictureManager->savePicture($request->file('avatar'), config('folders.training_pictures_folder'));
        
        if(!$path)
            $this->trainingRepository->store($data);
        else {
            $data = array_merge($data, ['avatar' => $path]);
            $this->trainingRepository->store($data);
        }

        return redirect()->route('training.index')->with(['success' => 'La filière '.$request->name.' a été ajoutée avec succès !']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $training = $this->trainingRepository->getById($id);
        $training_options = $training->options()->paginate($this->pagination);
        $links = $training_options->render();

        return view('trainings.show', compact('training', 'training_options', 'links'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $training = $this->trainingRepository->getById($id);
        $schools = $this->schoolRepository->getAll();

        return view('trainings.edit', compact('training', 'schools'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\TrainingRequest  $request
     * @param  App\Management\PictureManagement $pictureManager
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TrainingRequest $request, $id, PictureManagement $pictureManager)
    {
        $training = $this->trainingRepository->getById($id);
        $data = $request->except('avatar');
        $path = $pictureManager->updatePicture($training->avatar, $request->file('avatar'), config('folders.training_pictures_folder'));
        if(!$path)
            $this->trainingRepository->update($id, $data);
        else {
            $data = array_merge($data, ['avatar' => $path]);
            $this->trainingRepository->update($id, $data);
        }

        return redirect()->route('training.index')->with(['success' => 'Mise à jour effectuée avec succès !']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->trainingRepository->destroy($id);

        return back();
    }
}

resources/views/trainings/create.blade.php
@extends('back-end.main-layout')

@section('styles')
  <!-- Dropzone Css -->
  <link href="{{asset('back-end/plugins/dropzone/dropzone.css')}}" rel="stylesheet">
  <!-- Bootstrap Material Datetime Picker Css -->
  <link href="{{asset('back-end/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css')}}" rel="stylesheet" />
  <!-- Wait Me Css -->
  <link href="{{asset('back-end/plugins/waitme/waitMe.css')}}" rel="stylesheet" />
  <!-- Bootstrap Select Css -->
  <link href="{{asset('back-end/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />
@stop

@section('content')
<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2 class="text-center"> Ajout d'une nouvelle filière </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn btn-white btn-icon btn-round hidden-sm-down float-right m-l-10" type="button">
                    <i class="zmdi zmdi-plus"></i>
                </button>
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('back.home')}}"><i class="zmdi zmdi-home"></i> Oreo</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0);">Filières</a></li>
                    <li class="breadcrumb-item active">Créer</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="body">
                        <div class="row clearfix">
                            <form method="post" class="col-sm-12" action="{{route('school.store')}}" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <input name="name" type="text" class="form-control {{ $errors->has('name') ? 'has-danger' : '' }}" value="{{ old('name') }}" placeholder="Nom de la filière">
                                    @if ($errors->has('name'))
                                        <span class="text-danger" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <input name="code" type="text" class="form-control {{ $errors->has('code') ? 'has-danger' : '' }}" value="{{ old('code') }}" placeholder="Code de la filière">
                                    @if ($errors->has('code'))
                                        <span class="text-danger" role="alert">
                                            <strong>{{ $errors->first('code') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <textarea rows="7" name="description" class="form-control {{ $errors->has('description') ? 'has-danger' : '' }}" value="{{ old('description') }}" placeholder="Description">Description</textarea>
                                    @if ($errors->has('description'))
                                        <span class="text-danger" role="alert">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <input name="admissionFees" type="number" class="form-control {{ $errors->has('admissionFees') ? 'has-danger' : '' }}" value="{{ old('admissionFees') }}" placeholder="Frais d'admission' de la filière">
                                    @if ($errors->has('admissionFees'))
                                        <span class="text-danger" role="alert">
                                            <strong>{{ $errors->first('admissionFees') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <input name="fees" type="number" class="form-control {{ $errors->has('fees') ? 'has-danger' : '' }}" value="{{ old('fees') }}" placeholder="Frais de scolarité de la filière">
                                    @if ($errors->has('fees'))
                                        <span class="text-danger" role="alert">
                                            <strong>{{ $errors->first('fees') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <select name="school_id" id="school_id" class="form-control {{ $errors->has('school_id') ? 'has-danger' : '' }}" value="{{ old('school_id') }}">
                                        @foreach($schools as $school)
                                            <option value="{{$school->id}}">{{$school->name}}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('school_id'))
                                        <span class="text-danger" role="alert">
                                            <strong>{{ $errors->first('school_id') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <input name="avatar" type="file" class="form-control {{ $errors->has('avatar') ? 'has-danger' : '' }}" value="{{ old('avatar') }}" placeholder="Sélectionnez une image">
                                    @if ($errors->has('avatar'))
                                        <span class="text-danger" role="alert">
                                            <strong>{{ $errors->first('avatar') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary center">Valider</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@stop

@section('scripts')
  <script src="{{asset('back-end/plugins/autosize/autosize.js')}}"></script> <!-- Autosize Plugin Js -->
  <script src="{{asset('back-end/plugins/momentjs/moment.js')}}"></script> <!-- Moment Plugin Js -->
  <!-- Bootstrap Material Datetime Picker Plugin Js -->
  <script src="{{asset('back-end/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js')}}"></script>

  <script src="{{asset('back-end/js/pages/forms/basic-form-elements.js')}}"></script>
@stop

resources/views/trainings/index.blade.php
@extends('back-end.main-layout')
@section('content')
<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Toutes les filières
                <small>Welcome to Siabanni</small>
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn btn-white btn-icon btn-round hidden-sm-down float-right m-l-10" type="button">
                    <i class="zmdi zmdi-plus"></i>
                </button>
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('back.home')}}"><i class="zmdi zmdi-home"></i> Oreo</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0);">Filières</a></li>
                    <li class="breadcrumb-item active">Toutes</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-md-10 col-lg-10">
                <div class="card">
                    <div class="body">
                        @if (Session::has('success'))
                            <div class="alert alert-success text-center">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                <p>{{ Session::get('success') }}</p>
                            </div>
                        @endif

                        <h6>Liste des filières de Siabanni</h6>
                        <div class="table-responsive">
                            <table class="table table-hover m-t-20">
                                <thead>
                                    <th>#</th>
                                    <th>Nom</th>
                                    <th>Frais d'admission</th>
                                    <th>Frais de scolarité</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </thead>
                                <tbody>
                                    @foreach ($trainings as $training)
                                    <tr>
                                        <td>{{$training->id}}</td>
                                        <td>{{$training->name}}</td>
                                        <td>{{$training->admissionFees}}</td>
                                        <td>{{$training->fees}}</td>
                                        <td>{!! link_to_route('training.show', 'En savoir plus', [$training->id], ['class' => 'btn btn-success btn-block']) !!}</td>
                                        <td>{!! link_to_route('training.edit', 'Modifier', [$training->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
                                        <td>
                                            {!! Form::open(['method' => 'DELETE', 'route' => ['training.destroy', $training->id]]) !!}
                                                {!! Form::submit('Supprimer', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Vraiment supprimer cet utilisateur ?\')']) !!}
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="col-sm-12 text-center">
                            {!! $links !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@stop

resources/views/trainings/show.blade.php
@extends('back-end.main-layout')
@section('content')
<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12 text-center">
                <h2>Infos sur une filière
                <small>Welcome to Siabanni</small>
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn btn-white btn-icon btn-round hidden-sm-down float-right m-l-10" type="button">
                    <i class="zmdi zmdi-plus"></i>
                </button>
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('back.home')}}"><i class="zmdi zmdi-home"></i> Oreo</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0);">Filières</a></li>
                    <li class="breadcrumb-item active">{{$training->name}}</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="body">
                        <div class="row">
                            <p class="col-sm-4"><b>Nom : </b></p>
                            <p class="col-sm-7"> {{$training->name}} </p>
                        </div>
                        <div class="row">
                            <p class="col-sm-4"><b>Code : </b></p>
                            <p class="col-sm-7"> {{$training->code}} </p>
                        </div>
                        <div class="row">
                            <p class="col-sm-4"><b> Description : </b></p>
                            <p class="col-sm-7"> {{$training->description}} </p>
                        </div>
                        <div class="row">
                            <p class="col-sm-4"><b>Frais d'admission : </b></p>
                            <p class="col-sm-7"> {{$training->admissionFees}} </p>
                        </div>
                        <div class="row">
                            <p class="col-sm-4"><b>Frais de scolarité : </b></p>
                            <p class="col-sm-7"> {{$training->fees}} </p>
                        </div>
                        <div class="row">
                            <p class="col-sm-4"><b>Entité : </b></p>
                            <p class="col-sm-7">
                                {!! link_to_route('school.show', $training->school->name , [$training->school->id], ['class' => 'text-info']) !!}
                            </p>
                        </div>
                        <div class="row">
                            <p class="col-sm-4"> <b>Image : </b></p>
                            <div class="col-sm-7">
                                @if($training->avatar)
                                    <img src="{{asset($training->avatar)}}" alt="Training picture" class="img-responsive img-thumbnail">
                                @else
                                    <p>Non encore définie</p>
                                @endif
                            </div>
                        </div>
                        <br><br><br>
                        <h5 class="text-center">Liste des options disponibles</h5>
                        <div class="table-responsive">
                            <table class="table table-hover m-t-20">
                                <thead>
                                    <th>Nom</th>
                                    <th></th>
                                </thead>
                                <tbody>
                                    @foreach ($training_options as $training_option)
                                        <tr>
                                            <td>{{$training_option->name}}</td>
                                            <td>{!! link_to_route('option.show', 'En savoir plus', [$training_option->id], ['class' => 'btn btn-info btn-block']) !!}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="col-sm-12 text-center">
                            {!! $links !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@stop